[versions]
# Define your version strings here
foojay          = "1.0.0"
mixin           = "0.7-SNAPSHOT"
geckolib        = "4.8.4"
minecolonies    = "1.20.1-1.1.1274"
blockui         = "1.20.1-1.0.193"
domum           = "1.20.1-1.0.296"
multipiston     = "1.20-1.2.43-RELEASE"
structurize     = "1.20.1-1.0.816"

[libraries]
# --- Core Infrastructures ---
sponge-mixingradle = { group = "org.spongepowered", name = "mixingradle", version.ref = "mixin" }
geckolib-forge = { group = "software.bernie.geckolib", name = "geckolib-forge-1.20.1", version.ref = "geckolib" }

# --- MineColonies Sub-Dependency Stack ---
minecolonies    = { group = "com.ldtteam", name = "minecolonies", version.ref = "minecolonies" }
blockui         = { group = "com.ldtteam", name = "blockui", version.ref = "blockui" }
domum           = { group = "com.ldtteam", name = "domum_ornamentum", version.ref = "domum" }
multipiston     = { group = "com.ldtteam", name = "multipiston", version.ref = "multipiston" }
structurize     = { group = "com.ldtteam", name = "structurize", version.ref = "structurize" }
towntalk        = { group = "curse.maven", name = "towntalk-900364", version = "5355511" }

# --- Ad Astra Sub-Dependency Stack (CurseMaven) ---
adastra            = { group = "earth.terrarium.adastra", name = "ad_astra-forge-1.20.1", version = "1.15.20" }

[bundles]
minecolonies-stack = [
    "minecolonies",
    "blockui",
    "domum",
    "multipiston",
    "structurize",
    "towntalk"
]

[plugins]
# Standard plugins with proper IDs can go here
foojay-resolver = { id = "org.gradle.toolchains.foojay-resolver-convention", version.ref = "foojay" }
