name = "Avali Colonies Pack"
author = "Cynic"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ff4f50f86f9430986820531dd1a73816b27cebf5639c4025011509db7f11bea1"

[versions]
forge = "47.4.21"
minecraft = "1.20.1"
