name = "Avali Colonies Pack"
author = "Cynic"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5510df713eb5cc904593e9e824ec5050922251689f2882b91c5825698cdea2ad"

[versions]
forge = "47.4.21"
minecraft = "1.20.1"
