name = "Avali Colonies Pack"
author = "Cynic"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "99781ffa3e489b0859c6fcaf069be8d9f97359a4338d8382fa8a035d9de3b02a"

[versions]
forge = "47.4.21"
minecraft = "1.20.1"
