name: Packwiz Deployment Server

on:
  workflow_call:
  push:
    branches: [ "main" ]
    paths:
      - 'Modpack/**'
      - '!Modpack/.bin/**'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages-hosting"
  cancel-in-progress: true

jobs:
  host-distribution:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Re-index General Modpack Files
        run: |
          cd Modpack
          chmod +x .bin/packwiz
          ./.bin/packwiz refresh

      - name: Prepare Pages Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: './Modpack'

      - name: Push Live to Web Server
        id: deployment
        uses: actions/deploy-pages@v4